# Before commit rules:
# 1. Ruff check .
# 2. Ruff format . 
# 3. Check for trailing whitespaces 
#
# If you want u can also add the arg flag --fix for the checker.

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    #Ruff version. 
    rev: v0.16.8
    hooks:
      # Run the linter.
      - id: ruff-check 
      # types and args are optional.
      #types_or: [python, pyi]
      #args: [--fix]
      # Run the formatterr.    
      - id: ruff-format 
